### ISSUE TITLE
Is there any Transmit code example?

### ISSUE THREAD

**Issue by litamin** [luksal/ESP32-DMX-RX#20]
Even the readme says there is example code for BOTH Rx and Tx, but there is no Tx code or info anywhere.

**Comment by luksal** [comment]
No there isn't any plug and play example code.
It was never planned to publish the code as a library. Therefore, the first sentence in the readme means that you can use the code as an example to build something suitable for your project.

After a brief study of the library, however, it should not be particularly difficult to adapt the rx example accordingly. Feel free to contribute this example.

**Comment by litamin** [comment]
I see. Could it be using "DMX::Write(channel, value)" then? Is there anything else needed for transmitting, like a "send buffer to DMX" that some libraries have at the end of their void loop code? Even a short sentance on how to Tx would be greatly appreciated.

**Comment by luksal** [comment]
Like the rx buffer, the tx buffer is handled by the library.

First use `DMX::Initialize(output)` instead of `DMX::Initialize(input)` and then use `DMX::Write(channel, value)` to set a single channel in the internal tx buffer or `WriteAll(uint8_t * data, uint16_t start, size_t size)` to set a whole block.

`DMX::Initialize(output)` creates a new thread, which automatically runs in the background and handles the uart.

But all this should be quickly apparent when reading the source code.
