### ISSUE TITLE
Use of xTaskCreate in dmx.cpp

### ISSUE THREAD

**Issue by macdroid53** [luksal/ESP32-DMX-RX#7]
Sorry, once again I'm probably showing my limited understanding of how this example fits in the VSC/PIO/ESP-IDF and the Arduino IDE.
(note: I'm running SimpleRX in VSC/PIO so I added #include Arduino and named it .cpp)

In SimpleDMX.ino the dmx.h is included.

In dmx.cpp the Initialize function calls xTaskCreate. But, I never see the freetos scheduler started. Does this happen automagically? (I'm just learning freertos...so this may be obvious and I just haven't grokked it yet...)

**Comment by luksal** [comment]
When your are running Arduino, the freertos scheduler ist automatically started after the setup function. Because ESP-IDF is running in the background of the Arduino infrastructure.
If you are running plain ESP-IDF, then you have to manually start the scheduler and take care of the watchdog in your main loop.
